### PR TITLE
About page

### PR DESCRIPTION
**Pull request by OmkarPh**
Signed-off-by: Omkar Phansopkar <omkarphansopkar@gmail.com>

### CODE REVIEW

**Comment by Aniruddha-Shriwant** [comment]
@OmkarPh why everything starts looking smaller? 

image

**Comment by OmkarPh** [comment]
Fixing that :)

**Comment by Aniruddha-Shriwant** [comment]
> Fixing that :)

Okay :)

**Comment by OmkarPh** [comment]
Fixed that :)

**Pull request merged**
